# Generated by Django 3.2 on 2024-12-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_alter_user_is_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisher',
            new_name='category',
        ),
    ]
