# Generated by Django 5.1.4 on 2024-12-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='bookapp/profile_pics/'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
